name: VC1_MLP
instantiate_config:
  _target_: lift3d.models.VisionGuidedMLP
  image_encoder:
    _target_: lift3d.models.VC1Encoder
    model_name: vc1_vitb  # ViT-B/32, ViT-L/14
    freeze: True
  image_dropout_rate: 0.0
  robot_state_dropout_rate: 0.0
  policy_hidden_dims: [256, 256, 256]
  policy_head_init_method: orthogonal
